CREATE ROLE fstrub LOGIN INHERIT;
CREATE ROLE hvries LOGIN INHERIT;
CREATE ROLE mkadmin NOINHERIT;
CREATE ROLE mkuser NOINHERIT;
GRANT mkadmin TO fstrub;
GRANT mkadmin TO hvries;

ALTER ROLE mkadmin WITH CREATEDB;

CREATE DATABASE mkdb OWNER mkadmin;

ALTER USER <user_name> WITH ENCRYPTED PASSWORD 'password';
